package com.wq.mkcode.pojo;

import java.util.Date;

public class RecruitDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.id
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.jobname
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String jobname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.salary
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.condition
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.education
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.type
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.address
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.eid
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.createtime
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.state
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.url
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.label
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.content1
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String content1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.content2
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    private String content2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.id
     *
     * @return the value of tb_recruit.id
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.id
     *
     * @param id the value for tb_recruit.id
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.jobname
     *
     * @return the value of tb_recruit.jobname
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.jobname
     *
     * @param jobname the value for tb_recruit.jobname
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setJobname(String jobname) {
        this.jobname = jobname == null ? null : jobname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.salary
     *
     * @return the value of tb_recruit.salary
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.salary
     *
     * @param salary the value for tb_recruit.salary
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.condition
     *
     * @return the value of tb_recruit.condition
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.condition
     *
     * @param condition the value for tb_recruit.condition
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.education
     *
     * @return the value of tb_recruit.education
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.education
     *
     * @param education the value for tb_recruit.education
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.type
     *
     * @return the value of tb_recruit.type
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.type
     *
     * @param type the value for tb_recruit.type
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.address
     *
     * @return the value of tb_recruit.address
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.address
     *
     * @param address the value for tb_recruit.address
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.eid
     *
     * @return the value of tb_recruit.eid
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.eid
     *
     * @param eid the value for tb_recruit.eid
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.createtime
     *
     * @return the value of tb_recruit.createtime
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.createtime
     *
     * @param createtime the value for tb_recruit.createtime
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.state
     *
     * @return the value of tb_recruit.state
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.state
     *
     * @param state the value for tb_recruit.state
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.url
     *
     * @return the value of tb_recruit.url
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.url
     *
     * @param url the value for tb_recruit.url
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.label
     *
     * @return the value of tb_recruit.label
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.label
     *
     * @param label the value for tb_recruit.label
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.content1
     *
     * @return the value of tb_recruit.content1
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getContent1() {
        return content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.content1
     *
     * @param content1 the value for tb_recruit.content1
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setContent1(String content1) {
        this.content1 = content1 == null ? null : content1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.content2
     *
     * @return the value of tb_recruit.content2
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public String getContent2() {
        return content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.content2
     *
     * @param content2 the value for tb_recruit.content2
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    public void setContent2(String content2) {
        this.content2 = content2 == null ? null : content2.trim();
    }
}