package com.wq.mkcode.dao;

import com.wq.mkcode.pojo.RecruitDao;
import java.util.List;

public interface RecruitDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    int insert(RecruitDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    RecruitDao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    List<RecruitDao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbg.generated Thu Jul 16 08:23:57 CST 2020
     */
    int updateByPrimaryKey(RecruitDao record);
}